import { useDialog } from '../lib/useDialog';
import { Lightbulb, X } from 'lucide-react';

export function ImageResultModal({ src, model, onClose }: {
  src: string;
  model: string;
  onClose: () => void;
}) {
  const dialogRef = useDialog<HTMLElement>(onClose);

  return (
    <div className="modal-backdrop" role="presentation" onClick={onClose}>
      <section
        ref={dialogRef}
        className="run-warning-modal advanced-lab-preview-modal"
        role="dialog"
        aria-modal="true"
        aria-label={`Image generated by ${model}`}
        onClick={(event) => event.stopPropagation()}
      >
        <div className="modal-title">
          <Lightbulb aria-hidden="true" />
          <div>
            <span>Image Lab result</span>
            <strong>{model}</strong>
          </div>
          <button type="button" className="mini-button outline" onClick={onClose}>
            <X aria-hidden="true" />
            Close
          </button>
        </div>
        <img className="advanced-lab-generated-image" src={src} alt={`Generated by ${model}`} />
      </section>
    </div>
  );
}
